name: Auto-Build Custom Caddy

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: airopi/caddy-l4

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest Caddy version from Docker Hub
        id: caddy_version
        run: |
          LATEST=$(curl -sL "https://hub.docker.com/v2/repositories/library/caddy/tags?page_size=100" | \
            jq -r '.results[].name' | \
            grep -x -E '[0-9]+\.[0-9]+\.[0-9]+' | \
            sort -V | tail -n 1)
          
          echo "Latest upstream Caddy version is: $LATEST"
          echo "version=$LATEST" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Check if we already built this version
        id: check_image
        run: |
          if docker manifest inspect ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:${{ steps.caddy_version.outputs.version }} > /dev/null 2>&1; then
            echo "Image ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:${{ steps.caddy_version.outputs.version }} already exists. Skipping build."
            echo "build_needed=false" >> $GITHUB_OUTPUT
          else
            echo "New version detected. Proceeding to build."
            echo "build_needed=true" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        if: steps.check_image.outputs.build_needed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        if: steps.check_image.outputs.build_needed == 'true'
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          build-args: |
            version=${{ steps.caddy_version.outputs.version }}
          tags: |
            ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:${{ steps.caddy_version.outputs.version }}
            ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:latest
